version: '3.8'

services:
 php:
    container_name: phpc
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./public:/usr/local/apache2/htdocs
    working_dir: /usr/local/apache2/htdocs
 apache:
      container_name: apachec
      build: ./docker/apache
      ports:
        - "8000:80"
      volumes:
        - ./:/usr/local/apache2/htdocs
 db:
    container_name: mysqlc
    image: mysql:8.0
    volumes:
      - ./database/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: test
      # MYSQL_USER: user
      # MYSQL_PASSWORD: test
      # 3308 is my port of my pick , 3306 is the default listen container port
    ports:
      - 3308:3306
